version: '3'
services:

  gatewaysfake:
    container_name: 'gatewaysfakes'
    image: 'jordihofc/gatewaysfakes'
    ports:
      - 8082:8083
    environment:
      DB_URL: jdbc:postgresql://postgres_gateways_fake/pedido
  postgres_desafio:
    container_name: 'BD_Principal'
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagamento
  postgres_gateways_fake:
    container_name: 'pedido'
    image: 'postgres:alpine'
    volumes:
      - postgres_pedido-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pedido
volumes:
  postgres-volume:
  postgres_pedido-volume:
